### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by Stianhn** [aaronksaunders/rn-cloudinary-demo#1]
First I would just like to say that it's awesome that you made this module. But why are you calling the project a demo? Sorry if the question is stupid, but I can't seem to find the "react-native-cloudinary" project?

**Comment by aaronksaunders** [comment]
the code was just a demo to validate writing a module, it works... but if you look at the todo list in the readme, there is some basic functionality missing that I think should be included before posting it to npm

**Comment by Stianhn** [comment]
OK. I'll take a look it and see if I can create a PR.
